package vsys.blockchain.transaction

object TransactionStatus extends Enumeration {
  val Unprocessed = Value(1)
  val Success = Value(2)
  val Failed = Value(3)
  val ContendFailed = Value(4)
  val InvalidContract = Value(5)
  val InvalidContractAddress = Value(6)
  val InvalidDataEntry = Value(7)
  val InvalidFunctionIndex = Value(8)
  val ContractDataTypeMismatch = Value(9)
  val ContractInvalidStateVariable = Value(10)
  val ContractStateVariableNotDefined = Value(11)
  val ContractInvalidOPCData = Value(12)
  val ContractUnsupportedOPC = Value(13)
  val ContractInvalidFunction = Value(14)
  val ContractInvalidTokenIndex = Value(15)
  val ContractInvalidAmount = Value(16)
  val ContractLocalVariableIndexOutOfRange = Value(17)
  val ContractTokenBalanceInsufficient = Value(18)
  val ContractTokenMaxExceeded = Value(19)
  val ContractInvalidTokenInfo = Value(20)
  val ContractUnsupportedWithdraw = Value(21)
  val ContractUnsupportedDeposit = Value(22)
  val ContractInvalidSigner = Value(23)
  val ContractInvalidCaller = Value(24)
  val ContractInvalidHash = Value(25)
  val ContractInvalidStateMap = Value(26)
  val ContractStateMapNotDefined = Value(27)
  val ContractMapValueInsufficient = Value(28)
}
