package vsys.transaction

object TransactionStatus extends Enumeration {
  val Unprocessed = Value(1)
  val Success = Value(2)
  val Failed = Value(3)
  val ContendFailed = Value(4)
  val InvalidContract = Value(5)
  val InvalidContractAddress = Value(6)
  val InvalidDataEntry = Value(7)
  val ContractDataTypeMissMatch = Value(8)
  val ContractInvalidStateVariable = Value(9)
  val ContractStateVariableNotDefined = Value(10)
  val ContractInvalidOPCData = Value(11)
  val ContractUnsupportedOPC = Value(12)
  val ContractInvalidFunction = Value(13)
  val ContractInvalidTokenIndex = Value(14)
  val ContractInvalidAmount = Value(15)
  val ContractLocalVariableIndexOutOfRange = Value(16)
  val ContractTokenBalanceInsufficient = Value(17)
  val ContractTokenMaxExceeded = Value(18)
  val ContractInvalidTokenInfo = Value(19)
  val ContractUnsupportedWithdraw = Value(20)
  val ContractUnsupportedDeposit = Value(21)
}
